#!/usr/bin/env Rscript

find_root <- function(args = commandArgs()) {
  re <- "^--file=(.+)$"
  i <- grep(re, args)
  stopifnot(length(i) >= 1)
  path_script <- normalizePath(sub(re, "\\1", args[[i[[1]]]]), mustWork = TRUE)
  dirname(path_script)
}


reload <- function(root) {
  paths <- dirname(list.files(root, recursive = TRUE, pattern = "^app.R$"))
  ok <- file.create(file.path(root, paths, "reload.txt"))
  if (any(ok)) {
    message(sprintf("Reloaded %d apps:\n%s",
                    sum(ok), paste("  -", paths[ok], collapse = "\n")))
  }
  if (any(!ok)) {
    message(sprintf("Failed to reload %d apps:\n%s",
                    sum(!ok), paste("  -", paths[!ok], collapse = "\n")))
  }
}


clear <- function(root) {
  paths <- list.files(root, recursive = TRUE, pattern = "^reload.txt$",
                      full.names = TRUE)
  unlink(paths)
  message(sprintf("Removed %d reload files", length(paths)))
}


parse_args <- function(args) {
  if (length(args) == 0) {
    clear <- FALSE
  } else if (identical(args, "--clear")) {
    clear <- TRUE
  } else {
    stop("Usage:\n  reload [--clear]")
  }
  list(clear = clear)
}


die <- function(msg) {
  message(msg)
  q(save = "no", status = 1)
}


main <- function(args = commandArgs(TRUE), root = find_root()) {
  opts <- tryCatch(
    parse_args(args),
    error = function(e) die(e$message))
  message("Working in ", root)
  if (opts$clear) {
    clear(root)
  } else {
    reload(root)
  }
}


if (!interactive()) {
  main()
}
