#!/usr/bin/env Rscript

find_root <- function(args = commandArgs()) {
  re <- "^--file=(.+)$"
  i <- grep(re, args)
  stopifnot(length(i) >= 1)
  path_script <- normalizePath(sub(re, "\\1", args[[i[[1]]]]), mustWork = TRUE)
  dirname(path_script)
}


reload <- function(root) {
  paths <- dirname(list.files(root, recursive = TRUE, pattern = "^app.R$"))
  ok <- file.create(file.path(root, paths, "reload.txt"))
  if (any(ok)) {
    message(sprintf("Reloaded %d apps:\n%s",
                    sum(ok), paste("  -", paths[ok], collapse = "\n")))
  }
  if (any(!ok)) {
    message(sprintf("Failed to reload %d apps:\n%s",
                    sum(!ok), paste("  -", paths[!ok], collapse = "\n")))
  }
}


clear <- function(root) {
  paths <- list.files(root, recursive = TRUE, pattern = "^reload.txt$",
                      full.names = TRUE)
  unlink(paths)
  message(sprintf("Removed %d reload files", length(paths)))
}


main <- function(root = find_root()) {
  args <- commandArgs(TRUE)
  if (length(args) == 0) {
    reload(root)
  } else if (identical(args, "--clear")) {
    clear(root)
  } else {
    message("Usage:\n  reload [--clear]")
    q(save = "no", status = 1)
  }
}


if (!interactive()) {
  main()
}
